"use client";

import { useEffect, useMemo, useState } from "react";
import AdminShell from "../../../components/admin/AdminShell";

type Employer = { id: string; name: string; email: string; role: "admin" | "user" | "employer"; employer_status: "none" | "pending" | "approved" | "rejected"; company_name?: string; company_website?: string; employer_reason?: string };

export default function AdminEmployersPage() {
  const [users, setUsers] = useState<Employer[]>([]);
  const [status, setStatus] = useState("all");
  const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/admin/users"); const data = await response.json(); if (!response.ok) return setError(data.error ?? "Unable to load employers"); setUsers((data.users ?? []).filter((user: Employer) => user.role === "employer" || user.employer_status !== "none")); }
  async function update(userId: string, value: string) { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId, employer_status: value, ...(value === "approved" ? { role: "employer" } : { role: "user" }) }) }); const data = await response.json(); if (!response.ok) setError(data.error ?? "Unable to update employer"); else setUsers((current) => current.map((user) => user.id === userId ? data.user : user)); }
  useEffect(() => { void load(); }, []);
  const employers = useMemo(() => status === "all" ? users : users.filter((user) => user.employer_status === status), [status, users]);
  return <AdminShell title="Employers" eyebrow="Verification operations"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[0.18em] text-[#e15a3d]">Employer network</p><h1 className="text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Employers</h1><p className="mt-2 text-sm text-slate-500">Review applications and control who can publish jobs.</p></div><select className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm" onChange={(event) => setStatus(event.target.value)} value={status}><option value="all">All employers</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div>{error && <p className="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700" role="alert">{error}</p>}<div className="grid gap-4">{employers.map((user) => <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm" key={user.id}><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-bold">{user.company_name || "Unnamed company"}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-slate-600">{user.employer_status}</span></div><p className="mt-2 text-sm text-slate-500">{user.name} · {user.email}</p>{user.company_website && <a className="mt-2 block text-sm text-[#e15a3d]" href={user.company_website} rel="noreferrer" target="_blank">{user.company_website} ↗</a>}</div><select className="h-10 rounded-lg border border-slate-200 px-3 text-sm font-bold" onChange={(event) => void update(user.id, event.target.value)} value={user.employer_status}><option value="pending">Pending</option><option value="approved">Approve</option><option value="rejected">Reject</option><option value="none">Remove employer status</option></select></div>{user.employer_reason && <p className="mt-5 max-w-3xl border-t border-slate-100 pt-5 text-sm leading-6 text-slate-600">{user.employer_reason}</p>}</article>)}{!employers.length && <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">No employer records match this status.</div>}</div></AdminShell>;
}
